name: Foodlify
description: A Very Good Project created by Very Good CLI.
version: 1.1.4+32
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  device_preview: ^1.1.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  injectable_generator: ^2.1.4
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  logger: ^2.0.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  dia: ^0.1.3
  dio: ^5.0.0
  flutter_secure_storage: ^9.0.0
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  gap: ^3.0.1
  flutter_svg: ^2.0.4
  webview_flutter: ^4.0.7
  pin_code_fields: ^8.0.1
  dotted_line: ^3.1.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  another_flushbar: ^1.12.29
  geolocator: ^10.0.0
  shared_preferences: ^2.1.1
  story_view: ^0.15.0
 
  freezed_annotation: ^2.2.0
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  lottie: ^2.5.0
  flutter_slidable: ^3.0.0
  share: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_timer_countdown: ^1.0.5
  change_app_package_name: ^1.1.0
  cached_network_image: ^3.2.3
  timer_count_down: ^2.2.2
  file_picker: ^5.5.0
  upgrader: ^8.1.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  in_app_update: ^4.2.2
  onesignal_flutter: ^5.0.3

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  freezed: ^2.3.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/foodlifyLogo.png"
  image_path_ios: "assets/images/foodlifyLogo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/foodlifyLogo.png
  

  android_12:
    image: assets/images/foodlifyLogo.png
    icon_background_color: "#ffffff"
    

  web: false
